# gudhi-xcframework-builder — thin wrapper over build.sh.

.PHONY: all xcframework clean distclean

all: xcframework

# Build Gudhi.xcframework (macOS arm64 static-library).
xcframework:
	./build.sh

# Remove only the assembled outputs (keeps the staged GUDHI headers).
clean:
	rm -rf output/Gudhi.xcframework output/Gudhi.xcframework.zip \
	       output/Gudhi.xcframework.zip.sha256 work/stage

# Remove everything regenerated by build.sh.
distclean: clean
	rm -rf work
